In [3]:
import numpy as np
import pandas as pd

In [10]:
np.random.seed(123)  # for reproducibility

In [7]:
asample2 = pd.read_csv("../data/asample2_withlag.csv")
asample2

,Cm_ltotalincome,Cm_lhourlywage,Cm_lfamilyincome,Cm_pemployed,Cm_sei,flag_unemp,Bset1_year1,Bset1_doi_employed1,Bset1_doi_employedmf1,Bset1_doi_hours_worked1,...,Aset1_Motherocc2_1979_4,Aset1_Motherocc2_1979_5,Aset1_Motherocc2_1979_7,Aset1_Motherocc2_1979_8,Aset1_Motherocc2_1979_9,Aset1_Motherocc2_1979_10,Aset1_mfFatherocc2_1979_0,Aset1_mfFatherocc2_1979_1,Aset1_mfMotherocc2_1979_0,Aset1_mfMotherocc2_1979_1
0,4.217487,1.977451,9.881452,0.666667,22.100000,0,1984,1,0,2,...,0,0,0,0,0,0,1,0,1,0
1,5.129690,1.991274,10.861930,1.000000,35.947498,0,1987,0,0,0,...,0,0,0,0,0,1,1,0,1,0
2,10.969552,3.398430,11.380778,1.000000,39.470001,0,1986,1,0,2,...,1,0,0,0,0,0,1,0,1,0
3,6.615533,2.511609,10.002362,0.333333,28.196667,0,1990,1,0,1,...,1,0,0,0,0,0,0,1,1,0
4,10.207645,2.567574,10.332740,1.000000,42.114998,0,1984,1,0,2,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7458,9.654572,1.816562,9.763045,1.000000,48.759998,0,1987,1,0,2,...,0,0,0,0,0,0,1,0,1,0
7459,0.000000,1.405642,0.000000,0.000000,15.074862,1,1982,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7460,9.327805,2.223070,10.282804,1.000000,16.370001,0,1984,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7461,10.226488,2.260700,10.944498,1.000000,18.678333,0,1988,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7462,5.965204,2.058554,8.289134,0.833333,39.436665,0,1984,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [8]:
# need to subsample data 

samp = asample2.loc[np.random.choice(asample2.index, 5, replace=False)]

In [9]:
samp

,Cm_ltotalincome,Cm_lhourlywage,Cm_lfamilyincome,Cm_pemployed,Cm_sei,flag_unemp,Bset1_year1,Bset1_doi_employed1,Bset1_doi_employedmf1,Bset1_doi_hours_worked1,...,Aset1_Motherocc2_1979_4,Aset1_Motherocc2_1979_5,Aset1_Motherocc2_1979_7,Aset1_Motherocc2_1979_8,Aset1_Motherocc2_1979_9,Aset1_Motherocc2_1979_10,Aset1_mfFatherocc2_1979_0,Aset1_mfFatherocc2_1979_1,Aset1_mfMotherocc2_1979_0,Aset1_mfMotherocc2_1979_1
3404,10.930220,3.189734,11.256371,1.0,49.470001,0,1984,1,0,2,...,0,0,0,0,0,0,1,0,1,0
3470,7.928235,2.561764,10.305248,0.8,32.029999,0,1989,1,0,2,...,0,0,0,0,0,1,1,0,1,0
4346,9.260012,1.522448,10.393841,1.0,39.093334,0,1984,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7239,9.137973,2.112319,10.130123,1.0,32.669998,0,1987,1,0,2,...,0,0,0,0,0,1,1,0,1,0
1045,10.643664,3.009559,11.109549,1.0,32.669998,0,1987,1,0,2,...,0,0,0,0,0,0,0,1,1,0

In [21]:
# training/test split - use 70/30 as in paper

n = len(asample2)
train_idx = np.random.choice(asample2.index, size=int(0.7 * n), replace=False)
test_idx = asample2.index.difference(train_idx)

X = asample2.drop('Cm_ltotalincome', axis=1)
y = asample2['Cm_ltotalincome']

X_train = X.loc[train_idx]
X_test = X.loc[test_idx]

y_train = y.loc[train_idx]
y_test = y.loc[test_idx]

In [16]:

print(asample2.dtypes)

Cm_ltotalincome              float64
Cm_lhourlywage               float64
Cm_lfamilyincome             float64
Cm_pemployed                 float64
Cm_sei                       float64
                              ...
Aset1_Motherocc2_1979_10       int64
Aset1_mfFatherocc2_1979_0      int64
Aset1_mfFatherocc2_1979_1      int64
Aset1_mfMotherocc2_1979_0      int64
Aset1_mfMotherocc2_1979_1      int64
Length: 4258, dtype: object

In [17]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /Users/ava/aleatoric-luck/aleatoric-luck/.venv/lib/python3.13/site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /Users/ava/aleatoric-luck/aleatoric-luck/.venv/lib/python3.13/site-packages (from lightgbm) (2.4.4)
Requirement already satisfied: scipy in /Users/ava/aleatoric-luck/aleatoric-luck/.venv/lib/python3.13/site-packages (from lightgbm) (1.17.1)

In [22]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_error

model = lgb.LGBMRegressor(
    n_estimators = 100,
    max_depth = 3,
    learning_rate=0.1
)

model.fit(X_train, y_train)
preds = model.predict(X_test)
mse = mean_squared_error(y_test, preds)

OSError: dlopen(/Users/ava/aleatoric-luck/aleatoric-luck/.venv/lib/python3.13/site-packages/lightgbm/lib/lib_lightgbm.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib
  Referenced from: <D44045CD-B874-3A27-9A61-F131D99AACE4> /Users/ava/aleatoric-luck/aleatoric-luck/.venv/lib/python3.13/site-packages/lightgbm/lib/lib_lightgbm.dylib
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/local/lib/libomp/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libomp/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/local/lib/libomp/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libomp/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file), '/opt/homebrew/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libomp.dylib' (no such file)